import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/util/theme-provider";
import { auth } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}

          <div className="absolute top-4 right-4">{session?.user?.email}</div>
        </ThemeProvider>
      </body>
    </html>
  );
}
