import { ToBuy } from "@/components/planned-columns";

export const toBuyList: ToBuy[] = [
  {
    id: "1",
    title: "Barra de chocolate para sobremesas deliciosas",
    price: 360,
    quantity: 3,
    status: "purchased",
    priority: "medium",
  },
  {
    id: "2",
    title: "Molho teriyaki para receitas orientais saborosas",
    price: 600,
    quantity: 2,
    status: "pending",
    priority: "high",
  },
  {
    id: "3",
    title: "Sacos de lixo para descarte de residuos queimaveis",
    price: 230,
    quantity: 2,
    status: "canceled",
    priority: "high",
  },
  {
    id: "4",
    title: "Meias confortáveis para uso diário ou esportivo",
    price: 300,
    quantity: 3,
    status: "pending",
    priority: "medium",
  },
  {
    id: "5",
    title: "Garrafas de água mineral para hidratação diária",
    price: 230,
    quantity: 2,
    status: "purchased",
    priority: "high",
  },
  {
    id: "6",
    title: "Lata de refrigerante Coca-Cola para momentos refrescantes",
    price: 240,
    quantity: 1,
    status: "purchased",
    priority: "high",
  },
  {
    id: "7",
    title: "Figura de anime Frieren para colecionadores apaixonados",
    price: 3200,
    quantity: 1,
    status: "canceled",
    priority: "low",
  },
  {
    id: "8",
    title: "Colher dourada de luxo para ocasiões especiais",
    price: 30000,
    quantity: 1,
    status: "canceled",
    priority: "low",
  },
];
